name = "kings-league-api"
main = "api/index.js"
compatibility_date = "2023-01-03"

[site]
bucket = "./assets"

[env.production]
vars = { ENVIRONMENT = "production" }
routes = [
  { pattern = "api.kingsleague.dev", custom_domain = true }
]